### ISSUE TITLE
[1.20.1] Incompatible With Quark

### ISSUE THREAD

**Issue by RConTRS** [ochotonida/artifacts#242]
when using quark, the mimic will have black&purple texture

artifacts-forge-9.2.1
architectury-9.1.12-forge
forge 1.20.1 - 47.2.20

the only thing that refrenced artifacts/mimic in the log is

[Render thread/WARN] [dev.architectury.registry.registries.forge.RegistrarManagerImpl/]: Registry entry listened Registry Entry [minecraft:entity_type / artifacts:mimic] was not realized!

**Comment by etherealgears** [comment]
This can be fixed by setting "useModdedMimicTextures" to "false" in artifacts/client.json5, but that means you only get Mimics with the vanilla chest skin, no modded skins.

**Comment by RConTRS** [comment]
ok closing the issue since it will remain on quark's end, might be fixed by itself when quark becomes more stable or something i don't really know.

**Comment by ochotonida** [comment]
You can keep this open, it's definitely an issue with Artifacts. I haven't taken a look at it yet but it should be a simple fix.

**Comment by ochotonida** [comment]
Fixed in version 9.2.2

**Comment by bookerthegeek** [comment]
### Heyo

Sadly this is still an issue

```
[19:56:37] [Render thread/WARN] [de.ar.re.re.fo.RegistrarManagerImpl/]: Registry entry listened Registry Entry [minecraft:entity_type / artifacts:mimic] was not realized!
```

- Minecraft: 1.20.1
- Forge: 47.4.10
- Artifacts: 9.5.16
- Lootr: 0.7.35.92
- Quark: 4.0-462

(Listed the other two mods due to them being mentioned in .../artifacts/client.json5)

**Comment by ochotonida** [comment]
Thanks for letting me know, I'll take another look.

**Comment by ochotonida** [comment]
I can't reproduce the issue using just the mod versions you listed, so there's very likely another mod involved. If there's nothing else that sticks out in the log, you might have to start removing mods until you find the one that's causing the issue.

**Comment by bookerthegeek** [comment]
I will do so this weekend.

**Comment by bookerthegeek** [comment]
Sorry for jumping onto the Quark bandwagon. Turns out my issue was caused by KubeJS. The above mention is where all the relevant information is at.
